services:
  db:
    image: mysql:lts
    restart: always
    environment:
      MYSQL_DATABASE: 'bibliodb'
      MYSQL_ROOT_PASSWORD: 'bibliorootpswd'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
